# Generated by Django 5.2.7 on 2026-01-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplierpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='updated_by',
        ),
    ]
