# Generated by Django 5.2.7 on 2026-01-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplierpayment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='deleted_at',
        ),
    ]
