# Generated by Django 5.2.7 on 2026-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_remove_supplierpayment_deleted_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(fields=('supplier', 'payment_date', 'amount'), name='unique_supplier_payment_date_amount'),
        ),
    ]
