# Generated by Django 5.2.7 on 2026-01-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplierpayment_unique_supplier_payment_date_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
