# Generated by Django 5.2.7 on 2026-01-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(help_text="Employee's monthly salary"),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.IntegerField(help_text='Salary amount'),
        ),
    ]
