# Generated by Django 5.2.7 on 2026-01-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_reason', models.CharField(choices=[('SICK', 'Sick Leave'), ('FAMILYSICK', 'Family Sick Leave'), ('CASUAL', 'Casual or personal Leave'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_date'), name='unique_employee_leave_date')],
            },
        ),
    ]
