# Generated by Django 5.2.7 on 2026-01-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(choices=[('Shab-e-Barat', 'Shab-e-Barat'), ('Eid-e-Milad-un-Nabi', 'Eid-e-Milad-un-Nabi'), ('Pohela Boishakh', 'Pohela Boishakh'), ('Shaheed Dibosh & International Mother Language Day', 'Shaheed Dibosh & International Mother Language Day'), ('Shab-e-Qadr', 'Shab-e-Qadr'), ('Independence Day', 'Independence Day'), ('May Day', 'May Day'), ('Eid al-Fitr', 'Eid al-Fitr'), ('Eid al-Adha', 'Eid al-Adha'), ('Durga Puja', 'Durga Puja'), ('July Mass-uprising Day', 'July Mass-uprising Day'), ('Janmashtami', 'Janmashtami'), ('Buddha Purnima', 'Buddha Purnima'), ('Christmas Day', 'Christmas Day'), ('Victory Day', 'Victory Day'), ('Condolence', 'Condolence'), ('Others', 'Others')], help_text='Fixed day of the year for holiday', max_length=250),
        ),
    ]
