# Generated by Django 5.2.7 on 2026-01-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSaleReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PRICE_HIGH', 'Price Too High'), ('NO_STOCK', 'Product Not Available'), ('INQUIRY', 'Inquiry Only'), ('COMPARE', 'Comparing Prices'), ('LATER', 'Will Buy Later'), ('LEFT_WITHOUT_REASON', 'Left Without Reason'), ('OUT_OF_BUDGET', 'Out of Budget'), ('WRONG_SPECIFICATION', 'Wrong Specification'), ('ANOTHER_BRAND', 'Looking for Another Brand'), ('URGENT_NEED_NOT_MET', 'Urgent Need Not Met'), ('OTHER', 'Other')], max_length=30)),
                ('visiting_date', models.DateField()),
                ('visiting_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_sale_visits', to='customers.customer')),
            ],
        ),
    ]
