# Generated by Django 5.2.7 on 2026-01-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_nosalereason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('contact_time', models.TimeField(blank=True, null=True)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=10)),
                ('response_type', models.CharField(choices=[('received', 'Call Received'), ('not_received', 'Call Not Received'), ('busy', 'Busy'), ('switched_off', 'Switched Off'), ('wrong_number', 'Wrong Number'), ('regular_customer', 'Regular Customer'), ('repeat_order', 'Repeat Order Confirmed'), ('visited_shop', 'Visited Shop'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('call_later', 'Asked to Call Later')], max_length=20)),
                ('next_contact_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
        ),
    ]
