DISTRICT_CHOICES = (
        ('Bagerhat', 'Bagerhat'),
        ('Bandarban', 'Bandarban'),
        ('Barguna', 'Barguna'),
        ('Barishal', 'Barishal'),
        ('Bhola', 'Bhola'),
        ('Bogura', 'Bogura'),
        ('Brahmanbaria', 'Brahmanbaria'),
        ('Chandpur', 'Chandpur'),
        ('Chapai Nawabganj', 'Chapai Nawabganj'),
        ('Chattogram', 'Chattogram'),
        ('Chuadanga', 'Chuadanga'),
        ('Comilla', 'Comilla'),
        ('Coxs Bazar', 'Coxs Bazar'),
        ('Cumilla', 'Cumilla'),
        ('Dhaka', 'Dhaka'),
        ('Dinajpur', 'Dinajpur'),
        ('Faridpur', 'Faridpur'),
        ('Feni', 'Feni'),
        ('Gaibandha', 'Gaibandha'),
        ('Gazipur', 'Gazipur'),
        ('Gopalganj', 'Gopalganj'),
        ('Habiganj', 'Habiganj'),
        ('Jamalpur', 'Jamalpur'),
        ('Jashore', 'Jashore'),
        ('Jhalokati', 'Jhalokati'),
        ('Jhenaidah', 'Jhenaidah'), 
        ('Joypurhat', 'Joypurhat'),
        ('Khagrachari', 'Khagrachari'),
        ('Khulna', 'Khulna'),
        ('Kishoreganj', 'Kishoreganj'),
        ('Kurigram', 'Kurigram'),
        ('Kushtia', 'Kushtia'),
        ('Lakshmipur', 'Lakshmipur'),
        ('Lalmonirhat', 'Lalmonirhat'),
        ('Madaripur', 'Madaripur'),
        ('Magura', 'Magura'),
        ('Manikganj', 'Manikganj'),
        ('Meherpur', 'Meherpur'),
        ('Moulvibazar', 'Moulvibazar'),
        ('Munshiganj', 'Munshiganj'),
        ('Mymensingh', 'Mymensingh'),
        ('Naogaon', 'Naogaon'),
        ('Narail', 'Narail'),
        ('Narayanganj', 'Narayanganj'),
        ('Narsingdi', 'Narsingdi'),
        ('Natore', 'Natore'),
        ('Netrokona', 'Netrokona'),
        ('Nilphamari', 'Nilphamari'),
        ('Noakhali', 'Noakhali'),
        ('Pabna', 'Pabna'),
        ('Panchagarh', 'Panchagarh'),
        ('Patuakhali', 'Patuakhali'),
        ('Pirojpur', 'Pirojpur'),
        ('Rajbari', 'Rajbari'),
        ('Rajshahi', 'Rajshahi'),
        ('Rangamati', 'Rangamati'),
        ('Rangpur', 'Rangpur'),
        ('Satkhira', 'Satkhira'),
        ('Shariatpur', 'Shariatpur'),
        ('Sherpur', 'Sherpur'),
        ('Sirajganj', 'Sirajganj'),
        ('Sunamganj', 'Sunamganj'),
        ('Sylhet', 'Sylhet'),
        ('Tangail', 'Tangail'),
        ('Thakurgaon', 'Thakurgaon')
)
COUNTRY_CHOICES = (
    ('Bangladesh', 'Bangladesh'),
    ('India', 'India'),
    ('China', 'China'),
    ('Japan', 'Japan'),
    ('Korea', 'Korea'),
    ('Taiwan', 'Taiwan')
)

MEASUREMENT_UNIT_CHOICES = (
        ('Piece', 'Piece'),
        ('Inch', 'Inch'),
        ('Meter', 'Meter'),
        ('Feet', 'Feet'),
        ('Packet', 'Packet')
)

PRODUCT_STATUS_CHOICES = [
    ('active', 'Active'),
    ('inactive', 'Inactive'),
    ('out_of_stock', 'Out of Stock'),
]

ORDER_STATUS_CHOICES = [
    ('complete', 'Complete'),
    ('return', 'Return'),
    ('cancel', 'Cancel'),
]

NO_SALE_REASON_CHOICES = [
        ('PRICE_HIGH', 'Price Too High'),
        ('NO_STOCK', 'Product Not Available'),
        ('INQUIRY', 'Inquiry Only'),
        ('COMPARE', 'Comparing Prices'),
        ('LATER', 'Will Buy Later'),
        ('LEFT_WITHOUT_REASON', 'Left Without Reason'),
        ('OUT_OF_BUDGET', 'Out of Budget'),
        ('WRONG_SPECIFICATION', 'Wrong Specification'),
        ('ANOTHER_BRAND', 'Looking for Another Brand'),
        ('URGENT_NEED_NOT_MET', 'Urgent Need Not Met'),
        ('OTHER', 'Other'),
]