# Generated by Django 5.2.7 on 2026-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBankingProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_date', models.DateField()),
                ('mobile_banking_category', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('BKASHPERSONAL', 'Bkash Personal'), ('NAGADPERSONAL', 'Nagad Personal'), ('ROCKETPERSONAL', 'Rocket Personal'), ('ROCKET', 'Rocket'), ('UPAY', 'Upay'), ('SURECASH', 'SureCash'), ('MCASH', 'mCash'), ('UPAY', 'Upay'), ('OTHER', 'Other')], max_length=20)),
                ('profit_amount', models.IntegerField(help_text='Profit earned from mobile banking')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
