# Generated by Django 5.2.7 on 2026-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(help_text='Expense amount'),
        ),
    ]
