# Generated by Django 5.2.7 on 2026-01-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer'),
        ('orders', '0002_rename_customer_id_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_date', 'memo_number', 'sale_amount'), name='unique_order_date_memo_number_sale_amount'),
        ),
    ]
