# Generated by Django 5.2.7 on 2026-01-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.IntegerField(help_text='Profit amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_amount',
            field=models.IntegerField(help_text='Sale amount'),
        ),
    ]
