# Generated by Django 5.2.7 on 2026-01-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0007_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('balance_amount', models.DecimalField(decimal_places=2, help_text='Final supplier balance after reconciliation', max_digits=14)),
                ('adjust_amount', models.DecimalField(decimal_places=2, help_text='Adjustment amount (+ / -)', max_digits=14)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='suppliers.supplier')),
            ],
        ),
    ]
