# Generated by Django 5.2.7 on 2026-01-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierreconciliation',
            name='adjust_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjustment amount (+ / -)', max_digits=14, null=True),
        ),
    ]
