# Generated by Django 5.2.7 on 2026-01-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_supplierreconciliation_adjust_amount'),
        ('suppliers', '0007_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierreconciliation',
            constraint=models.UniqueConstraint(fields=('supplier', 'reconciliation_date', 'balance_amount'), name='unique_supplier_reconciliation_date_balance'),
        ),
    ]
