# Generated by Django 5.2.7 on 2026-01-06 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_buying_price'),
        ('stocks', '0003_supplierreconciliation_unique_supplier_reconciliation_date_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_stock_quantity', models.IntegerField(help_text='Physical stock quantity at reconciliation')),
                ('adjust_quantity', models.IntegerField(help_text='Adjustment quantity (+ / -)')),
                ('reconciliation_price', models.DecimalField(decimal_places=2, help_text='Price used for reconciliation valuation', max_digits=14)),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='products.product')),
            ],
        ),
    ]
