# Generated by Django 5.2.7 on 2026-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_buying_price'),
        ('stocks', '0004_productreconciliation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productreconciliation',
            constraint=models.UniqueConstraint(fields=('product', 'reconciliation_date', 'physical_stock_quantity'), name='unique_product_reconciliation_date_physical_stock_quantity'),
        ),
    ]
