# Generated by Django 5.2.7 on 2026-01-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_productreconciliation_unique_product_reconciliation_date_physical_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreconciliation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
