# Generated by Django 5.2.7 on 2026-01-06 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_nosalereason'),
        ('stocks', '0006_productreconciliation_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_amount', models.IntegerField(help_text='Final receivable balance after reconciliation')),
                ('adjust_amount', models.IntegerField(help_text='Adjustment amount (+ / -)')),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='customers.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'reconciliation_date', 'updated_amount'), name='unique_customer_reconciliation_date_updated_amount')],
            },
        ),
    ]
