# Generated by Django 5.2.7 on 2026-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_customerreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('others', 'Others')], max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('reconciliation_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account_name', 'reconciliation_date'), name='unique_account_daily_recon_v3')],
            },
        ),
    ]
