# Generated by Django 5.2.7 on 2026-01-06 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_financialreconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreconciliation',
            name='reconciliation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierreconciliation',
            name='adjust_amount',
            field=models.IntegerField(default=0, help_text='Adjustment amount (+ / -)'),
        ),
        migrations.AlterField(
            model_name='supplierreconciliation',
            name='balance_amount',
            field=models.IntegerField(help_text='Final supplier balance after reconciliation'),
        ),
        migrations.AlterField(
            model_name='supplierreconciliation',
            name='reconciliation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
