# Generated by Django 5.2.7 on 2025-12-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
