# Generated by Django 5.2.7 on 2026-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_country_alter_producttype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='short_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='short_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='short_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
