# Generated by Django 5.2.7 on 2026-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_short_code_productcategory_short_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='short_code',
            field=models.TextField(blank=True, default='nb', unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='short_code',
            field=models.TextField(blank=True, default='nc', unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='short_code',
            field=models.TextField(blank=True, default='npt', unique=True),
        ),
    ]
